export enum MiscEnum {
    API_INCOMING_ENDPOINT = 'mirowebhppl',
    GET_BOARDS_BUTTON = 'Get Boards',
    GET_BOARDS_ACTION_ID = 'get-boards',
    BOARD_ACTIONS_BLOCK = 'board-actions',
	VIEW_BOARD_BUTTON = 'View',
    VIEW_BOARD_ACTION_ID = 'view-board',
    EDIT_BOARD_BUTTON = 'Edit',
    EDIT_BOARD_ACTION_ID = 'edit-board',
    SHARE_BOARD_BUTTON = 'Share',
    SHARE_BOARD_ACTION_ID = 'share-board',
    DELETE_BOARD_BUTTON = 'Delete',
    DELETE_BOARD_ACTION_ID = 'delete-board',
    SUBSCRIBE_BOARD_BUTTON = 'Subscribe',
    SUBSCRIBE_BOARD_ACTION_ID = 'subscribe-board',
    CREATE_BOARD_ACTION_ID = 'create-board',
    ADD_BOARD_MEMBERS_BUTTON = 'Add Members',
    ADD_BOARD_MEMBERS_ACTION_ID = 'add-board-members',
}
