export enum MiscEnum {
    API_INCOMING_ENDPOINT = 'mirowebhook',
    GET_BOARDS_BUTTON = 'Get Boards',
    GET_BOARDS_ACTION_ID = 'get-boards',
    BOARD_ACTIONS_BLOCK = 'board-actions',
	VIEW_BOARD_BUTTON = 'View',
    VIEW_BOARD_ACTION_ID = 'view-board',
    REMOVE_BOARD_EMBEDDING_BUTTON = 'Remove',
    REMOVE_BOARD_EMBEDDING_ACTION_ID = 'remove-embedding',
    EDIT_BOARD_BUTTON = 'Edit',
    EDIT_BOARD_ACTION_ID = 'edit-board',
    SHARE_BOARD_BUTTON = 'Share',
    SHARE_BOARD_ACTION_ID = 'share-board',
    DELETE_BOARD_BUTTON = 'Delete',
    DELETE_BOARD_ACTION_ID = 'delete-board',
    DELETE_SUBSCRIPTION_BUTTON = 'Delete',
    DELETE_SUBSCRIPTION_ACTION_ID = 'delete-subscription',
    SUBSCRIBE_BOARD_BUTTON = 'Subscribe',
    SUBSCRIBE_BOARD_ACTION_ID = 'subscribe-board',
    EMBED_BOARD_BUTTON = 'Embed',
    EMBED_BOARD_ACTION_ID = 'embed-board',
    CREATE_BOARD_ACTION_ID = 'create-board',
    ADD_BOARD_MEMBERS_BUTTON = 'Add Members',
    ADD_BOARD_MEMBERS_ACTION_ID = 'add-board-members',
    VIEW_EMBEDDED_BOARDS_ACTION_ID = 'view-embedded-boards'
}
