export enum ModalsEnum {
    OPTIONAL_PARAMETERS_LABEL = 'Optional Parameters',
    GET_BOARDS_MODAL_NAME = 'Fetch Boards',
    GET_BOARDS = 'get-boards',
    GET_BOARDS_WITH_ROOM = 'create-task-with-room',
    GET_BOARDS_LABEL = 'Get Boards',
    TEAM_ID_INPUT_LABEL = 'Enter Team ID',
    TEAM_ID_INPUT_LABEL_DEFAULT = 'enter the team ID here',
    TEAM_ID_INPUT = 'team-id',
    TEAM_ID_BLOCK = 'team-id-block',
    PROJECT_ID_BLOCK = 'project-id-block',
    PROJECT_ID_INPUT_LABEL = 'Enter Project ID',
    PROJECT_ID_INPUT_LABEL_DEFAULT = 'enter the project id here',
    PROJECT_ID_INPUT = 'project-id',
    QUERY_INPUT_LABEL = 'Enter query string to match',
    QUERY_INPUT_LABEL_DEFAULT = 'enter the words to match',
    QUERY_INPUT = 'query',
    QUERY_BLOCK = 'query-block',
    OWNER_ID_BLOCK = 'owner-id-block',
    OWNER_ID_INPUT_LABEL = 'Enter OWNER ID',
    OWNER_ID_INPUT_LABEL_DEFAULT = 'enter the OWNER id here',
    OWNER_ID_INPUT = 'owner-id',
    GET_BOARDS_SUBMIT_BUTTON_LABEL = 'Get Boards'
}